### ISSUE TITLE
Complex types are not preserved when transformed in `normalize`

### ISSUE THREAD

**Issue by IgnisDa** [Nikaple/nest-typed-config#122]
## I'm submitting a...

```
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
```

## Current behavior

Simple transformation in the `normalize` function work as expected, but converting them to other datatypes (for eg Uint8Array) does not work.

## Expected behavior

The types and values should be preserved.

## Minimal reproduction of the problem with instructions

Stackblitz: https://stackblitz.com/edit/nestjs-starter-demo-uus4oz?file=src/config.ts

In this example, I convert `TEST` into an `Uint8Array`. When I print that inside the function itself, I get the expected output. But doing so in a service does not give the correct output.

![image](https://user-images.githubusercontent.com/60938164/151149792-aab6db15-b366-4743-910f-183298cd9579.png)

## Environment

All environments

**Comment by Nikaple** [comment]
This module relies on `class-transformer` to transform plain config object to class instances, which [supports only plain arrays](https://github.com/typestack/class-transformer/blob/develop/src/TransformOperationExecutor.ts#L6). Also, it seems a bit uncommon to use Uint8Array in configurations. Anyway, I can provide a workaround with getter functions:

```ts
export class RootConfig {
  @Type(() => Number)
  @IsDefined()
  public readonly numbers!: number[];

  public get uint8() {
    return new Uint8Array(this.numbers);
  }
}
```

**Comment by Nikaple** [comment]
If javascript has a constructor function `Uint8` like `Number`, you can use `@Type(() => Uint8)` to create a `Uint8[]`. But sadly there isn't.

**Comment by IgnisDa** [comment]
Thank you, the getter method works. 

> Also, it seems a bit uncommon to use Uint8Array in configurations.

I am using it to load the Solana secret key from environment variables which is expected to be a `Uint8Array`.
