### ISSUE TITLE
Automatically assign environments from `.env` file to `process.env`

### ISSUE THREAD

**Issue by latipun7** [Nikaple/nest-typed-config#13]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

`imports: [TypeOrmModule.forRoot()]` (without passing a configuration object to `forRoot()`) is breaking even thought I [specify configuration in environment variables as `.env` file](https://typeorm.io/#/using-ormconfig/using-environment-variables).

## Expected behavior

Specifying TypeORM configuration as Environment Variables as `.env` file should pass and logged in to database with only `imports: [TypeOrmModule.forRoot()]` (without passing a configuration object to `forRoot()`).

## What is the motivation / use case for changing the behavior?

TypeORM accept [environment variables as configuration](https://typeorm.io/#/using-ormconfig/using-environment-variables) so it can't be used with dependency injection.

## Environment

<pre><code>
Nest version: 8.1.2

 
For Tooling issues:
- Node version: 16.13.0  
- Platform:  

Others:

</code></pre>

**Comment by Nikaple** [comment]
Closed by #14
