### ISSUE TITLE
Isuee : Default value is skipped in nested object when 1 or up property is define in env.

### ISSUE THREAD

**Issue by hotrungnhan** [Nikaple/nest-typed-config#141]
## I'm submitting a...bug

<pre><code>
[ ] Regression 
[x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Isuee : Default value is skipped in nested object when 1 or up property is define in env.

## Environment

<pre><code>
Nest version: 8.0.0
 
For Tooling issues:
- Node version: 14
- Platform: window

Others:
</code>
</pre>

**Comment by Nikaple** [comment]
This module relies on `class-transformer` to transform plain config object to class instances, please refer to [class-transformer's documentation](https://github.com/typestack/class-transformer/) first. If it still can not solve your problem, please provide a minimum reproduction repo, you can create on via [CodeSandbox](https://codesandbox.io/s/affectionate-tdd-1juv6?file=/src/config.ts).

**Comment by Nikaple** [comment]
Closed due to inactivity.
