### ISSUE TITLE
Matching between environment variables & config file properties

### ISSUE THREAD

**Issue by imkh** [Nikaple/nest-typed-config#148]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

I'm trying to replicate the same configuration capabilities as large open-source projects such as GitLab, Sourcegraph, or Kibana. In those projects, you have the ability to specify configuration via a config file (gitlab.yml, sourcegraph.json, kibana.yml) or an equivalent environment variable (with env variables having priority over the config file).

| GitLab | Sourcegraph | Kibana |
|---|---|---|
| [gitlab.yml](https://gitlab.com/gitlab-org/gitlab-foss/-/blob/e4011eb84527cb7fd46aa34e07a8cd33746c4a5a/config/gitlab.yml.example) | [admin/config/site.schema.json](https://docs.sourcegraph.com/admin/config/site_config) | [kibana.yml](https://github.com/elastic/kibana/blob/1eea7a32d4cac9a125c76eb967f05bd9d034ed2d/config/kibana.yml) |
| [Env variables](https://github.com/sameersbn/docker-gitlab/blob/f89a0be917442dd3b92e414f4ecffb33bbdf8c7a/docker-compose.yml#L40) | [Env variables](https://docs.sourcegraph.com/cli/explanations/env) | [Env variables](https://github.com/elastic/stack-docs/blob/f6bf85e251b3c8c8729553f8749cc3e9f1598faa/docs/en/getting-started/docker/.env) |

So far so good, by following the README, I was able to get to the same setup. The last thing I'm unable to replicate is the ability to have an env variable name that is different from a YML property, but still have the two match and reference the same configuration property. The main reason is that env variables are typically written in uppercase with underscores (`SERVER_NAME`) while YML or JSON properties are usually in lowercase & camelCase (`serverName` or `server.name`).

<details>
  <summary>For example with Kibana:</summary>
  <img src="https://user-images.githubusercontent.com/7500251/155413084-d00179ab-352c-4fe8-b92c-c9c6a85f4e14.png" />
</details>

There could be a few ways to implement something like this:
1. some kind of "middleware" that would translate `serverName` to `SERVER_NAME` or `database.url` to `DATABASE_URL` 
2. not sure if possible: export a custom decorator to add on top of the property in the Config class

```js
// config.ts
export class Config {
  @EnvVariable('SERVER_NAME')
  public readonly serverName!: string;
}
```

The second solution is inspired by something I was able to do with a Golang config library: https://github.com/gravitational/configure

```go
type Config struct {
    StringVar   string              `env:"STRING_VAR" cli:"string-var" yaml:"string_var"`
    BoolVar     bool                `env:"BOOL_VAR" cli:"bool_var" yaml:"bool_var"`
    IntVar      int                 `env:"INT_VAR" cli:"int_var" yaml:"int_var"`
    HexVar      hexType             `env:"HEX_VAR" cli:"hex_var" yaml:"hex_var"`
    MapVar      map[string]string   `env:"MAP_VAR" cli:"map_var" yaml:"map_var,flow"`
    SliceMapVar []map[string]string `env:"SLICE_MAP_VAR" cli:"slice_var" yaml:"slice_var,flow"`
}
```

An other Golang config library (https://github.com/peterbourgon/ff) opted for the first solution:

```
Additionally, the example will look in the environment for variables with a MY_PROGRAM prefix. Flag names
are capitalized, and separator characters are converted to underscores. In this case, for example,
MY_PROGRAM_LISTEN_ADDR would match to listen-addr.
```

**Comment by Nikaple** [comment]
> not sure if possible: export a custom decorator to add on top of the property in the Config class

To my knowledge it's not possible. This library uses `class-transformer` to transform raw config object to class instances, and `class-transformer` did not support to have multiple sources on one class property.

As for the workaround, you can choose to implement the logic of loading environmental variables with [custom loader](https://github.com/Nikaple/nest-typed-config#using-custom-loader):

```ts
@Module({
  imports: [
    TypedConfigModule.forRoot({
      schema: Config,
      load: [
        () => {
          const rawEnv = dotenvLoader();
          // The library offers `separator` option, but maybe that couldn't satisfy your needs
          // So just go ahead and implement your own logic `parseRawEnv`.
          return parseRawEnv(rawEnv);
        },
        fileLoader(),
      ],
    }),
  ],
})
export class AppModule {}
```

**Comment by imkh** [comment]
Thanks for the suggestion. I tried to implement this custom logic and it's mostly working (env and YML file configs are "merged", with env having priority over YML file so it overrides any config property that is defined in both)  but there are a few caveats.

1. It seems like `dotenvLoader()` is useless, at least in newer versions of NestJS. I created a new project, without `@nestjs/config` or any kind of config library, and it looks like NestJS loads the `.env` file by default. I noticed this behavior when I tried to pass the options `dotenvLoader({ ignoreEnvFile: true })` and it didn't have any effect. That's a bummer because I want to disable `.env` file loading when `NODE_ENV=production` but it doesn't seem possible.
2. I'd like to have strong typing as much as possible, so in the custom loader, I specify my RootConfig class as return type. That way, if I add a new property, I will get a compile error in case I forget to return it in the custom loader. The problem I'm encountering is that I also make use of custom getters in my RootConfig class, as shown in the README. This causes TypeScript to throw an error, because you must specify all properties when creating a new object, including the custom getters. But this kind of defeats the point of having the logic in a single location so I'm not sure what would be the ideal solution. In the meantime, I use `Omit` in the return type to exclude the custom getters.
3. For some reason, having a nested configuration in the RootConfig class with the `@ValidateNested()` decorator doesn't work. You must add the custom validate function shown in the README. It seems like someone else already ran into this problem in this [issue](https://github.com/Nikaple/nest-typed-config/issues/123#issuecomment-1023223225). The [README of `class-validator`](https://github.com/typestack/class-validator/tree/142af759fcd23c96eae78c147d2069beb6648a31#validating-nested-objects) does mention that `nested object must be an instance of a class, otherwise @ValidateNested won't know what class is target of validation.` so that might be the reason?

```bash
# .env (for example, in a production environment)

###################################################################
# Env variables configuration (credentials, secrets, tokens, etc.)
# Unavailable in config.yml file on purpose
###################################################################

# The PostgreSQL database connection URL.
DATABASE_URL="postgresql://johndoe:randompassword@localhost:5432/myDB?schema=public"

################################################################
# Server configuration
################################################################

# The port of the Server.
PORT=80

# The external URL of the Server (including http:// or https://)
SERVER_URL=https://api.example.com

# The external URL of the Front (including http:// or https://)
FRONT_URL=https://example.com

################################################################
# OpenID Connect configuration (optional)
################################################################

# The URL that points to the OpenID Connect provider. For example, https://example.com/auth/realms/your-realm.
OPENIDCONNECT_ISSUER=https://example.com/auth/realms/your-realm
# The client identifier as configured in the OpenID Connect service provider.
OPENIDCONNECT_CLIENT_ID=<dotenv_oidc_client_id>
# The client secret as configured in the OpenID Connect service provider.
OPENIDCONNECT_CLIENT_SECRET=<dotenv_oidc_client_secret>
# If set to true, the OpenID Connect provider attempts to auto discover the client options using <OPENIDCONNECT_ISSUER>/.well-known/openid-configuration.
OPENIDCONNECT_DISCOVERY=true
```

```yml
# my-app.yml (for example, in a development environment)

############################################
# Server configuration
############################################

# The port of the Server.
port: '8001'

# The external URL of the Server (including http:// or https://)
serverUrl: http://localhost:8001

# The external URL of the Front (including http:// or https://)
frontUrl: http://localhost:3000

############################################
# Auth providers configuration (optional)
############################################

auth:
  providers:
    openidconnect:
      # The URL that points to the OpenID Connect provider. For example, https://example.com/auth/realms/your-realm.
      issuer: https://example.com/auth/realms/your-realm
      # The client identifier as configured in the OpenID Connect service provider.
      clientId: <config-yml_oidc_client_id>
      # The client secret as configured in the OpenID Connect service provider.
      clientSecret: <config-yml_oidc_client_secret>
      # If set to true, the OpenID Connect provider attempts to auto discover the client options using <issuer>/.well-known/openid-configuration.
      discovery: false
```

```ts
// src/config/config.ts

import { CorsOptions } from '@nestjs/common/interfaces/external/cors-options.interface';
import { Type } from 'class-transformer';
import {
  IsBoolean,
  IsIn,
  IsOptional,
  IsPort,
  IsString,
  IsUrl,
  ValidateNested,
} from 'class-validator';

export class OpenIDConnectConfig {
  @IsUrl()
  public readonly issuer!: string;

  @IsString()
  public readonly clientId!: string;

  @IsString()
  public readonly clientSecret!: string;

  @IsBoolean()
  public readonly discovery!: boolean;
}

export class AuthProvidersConfig {
  @Type(() => OpenIDConnectConfig)
  @ValidateNested()
  @IsOptional()
  public readonly openidconnect?: OpenIDConnectConfig;
}

export class AuthConfig {
  @Type(() => AuthProvidersConfig)
  @ValidateNested()
  @IsOptional()
  public readonly providers: AuthProvidersConfig = new AuthProvidersConfig();
}

export class RootConfig {
  @IsPort()
  public readonly port!: string;

  @IsUrl({ require_tld: false })
  public readonly serverUrl!: string;

  @IsUrl({ require_tld: false })
  public readonly frontUrl!: string;

  public get cors(): CorsOptions {
    return {
      origin: [this.frontUrl],
      credentials: true,
    };
  }

  /**
   * Database configuration
   */

  @IsString()
  public get databaseUrl(): string {
    return process.env.DATABASE_URL;
  }

  /**
   * Auth config
   */

  @Type(() => AuthConfig)
  @ValidateNested()
  @IsOptional()
  public readonly auth: AuthConfig = new AuthConfig();
}

```

```ts
// src/config/config.module.ts

import { CorsOptions } from '@nestjs/common/interfaces/external/cors-options.interface';
import { plainToClass } from 'class-transformer';
import { validateSync } from 'class-validator';
import { fileLoader, TypedConfigModule } from 'nest-typed-config';
import { RootConfig } from './config';

// Needed to not override an undefined boolean env variable to false
function boolEnvVar(envVar: string): boolean {
  if (envVar !== undefined && envVar !== null) {
    return envVar === 'true';
  }
  return undefined;
}

export const ConfigModule = TypedConfigModule.forRoot({
  schema: RootConfig,
  // validate function is a copy-paste from the library's README: https://github.com/Nikaple/nest-typed-config/tree/f2c7d8e580d1ab5a1842a3c24828520f943a591a#custom-validate-function
  // For some reason, it's needed to make the @ValidateNested() decorator work. Otherwise, it throws an error: `unknownValue: an unknown value was passed to the validate function`
  // Solution found here: https://github.com/Nikaple/nest-typed-config/issues/123#issuecomment-1023223225
  // And here: https://github.com/typestack/class-validator/tree/142af759fcd23c96eae78c147d2069beb6648a31#validating-nested-objects
  validate: (rawConfig: any) => {
    const config = plainToClass(RootConfig, rawConfig);
    const schemaErrors = validateSync(config, {
      forbidUnknownValues: true,
      whitelist: true,
    });

    if (schemaErrors.length) {
      throw new Error(TypedConfigModule.getConfigErrorMessage(schemaErrors));
    }

    return config as RootConfig;
  },
  load: [
    // YML Config file loader
    fileLoader({ absolutePath: 'my-app.yml' }),
    // Custom env variable config loader (has higher priority over file loader)
    // We use custom loader instead of default dotenvLoader in order to use uppercase env variables.
    // More info here: https://github.com/Nikaple/nest-typed-config/issues/148
    (): Omit<RootConfig, 'cors' | 'databaseUrl'> => { // Need to use Omit here otherwise TypeScript required to re-define the custom getter in the return value. Defeats the purpose of having the logic in a single location in the Config class.

      // Useless? NestJS already loads .env for some reason
      // const rawEnv = dotenvLoader({
      //   envFilePath: '.env',
      //   ignoreEnvFile: process.env.NODE_ENV === 'production', // Doesn't seem to work, .env is always loaded
      // }),

      const hasOpenidconnectConfig =
        Object.keys(process.env).filter((env) =>
          env.startsWith('OPENIDCONNECT_'),
        ).length > 0;

      return {
        port: process.env.PORT,
        serverUrl: process.env.SERVER_URL,
        frontUrl: process.env.FRONT_URL,
        // get cors(): CorsOptions {
        //   return {
        //     origin: [this.frontUrl],
        //     credentials: true,
        //   };
        // },
        // get databaseUrl(): string {
        //   return process.env.DATABASE_URL;
        // },
        auth: {
          providers: {
            ...(hasOpenidconnectConfig && {
              openidconnect: {
                issuer: process.env.OPENIDCONNECT_ISSUER,
                clientId: process.env.OPENIDCONNECT_CLIENT_ID,
                clientSecret: process.env.OPENIDCONNECT_CLIENT_SECRET,
                discovery: boolEnvVar(process.env.OPENIDCONNECT_DISCOVERY),
              },
            }),
          },
        },
      };
    },
  ],
});
```

**Comment by Nikaple** [comment]
1. Maybe check other parts of your app which loads configuration? I've just tried creating a brand new app with `nest new`, and it didn't load env variables automatically.
2. Currently that's no way to distinguish a `property` with a `getter method` in TypeScript, so I guess the only way is to separate your getter methods in another class, or use the `Omit` helper like you already did.
	  ```ts
	  export class RootConfigBase {
	    host: string;
	    port: number;
	  }
	  export class RootConfig extends RootConfigBase {
	    get url() {}
	  }
	  // use RootConfig for injection
	  // and use RootConfigBase for return value of custom loader
	  ```
4. According to the [code](https://github.com/Nikaple/nest-typed-config/blob/main/lib/typed-config.module.ts#L43), there should be no difference with builtin `validate` function and custom `validate` function. If you have further questions, please provide a [minimum reproduction repo](https://minimum-reproduction.wtf/).

**Comment by imkh** [comment]
1. You're right, I investigated a little more and found that it's [Prisma](https://docs.nestjs.com/recipes/prisma) that loads the `.env` file by default. Unfortunately, it doesn't seem like this behavior is [configurable](https://www.prisma.io/docs/guides/development-environment/environment-variables/managing-env-files-and-setting-variables). Well, at least now I know that if you have a project that uses Prisma, you can skip the `dotenv` library or the `dotenvLoader()` in `nest-typed-config` (unless you want to load an alternative env file such as `.env.development`)
2. Yeah, I also thought of separating the getters in another class, but then it makes it impossible to have custom getters in a nested config class (though it's the same with `Omit`). A solution I found that would work with getters in nested classes is to simply set the getters to any value such as `undefined`. It doesn't seem to have any undesirable side effect (the getter internal logic in the class will still work) and it gets rid of the TypeScript error.
```ts
// src/config/config.module.ts

// ...

export const ConfigModule = TypedConfigModule.forRoot({
  // ...
  load: [
    // ...
    (): RootConfig => {
      return {
        port: process.env.PORT,
        serverUrl: process.env.SERVER_URL,
        frontUrl: process.env.FRONT_URL,
        cors: undefined,
        // get cors(): CorsOptions {
        //   return {
        //     origin: [this.frontUrl],
        //     credentials: true,
        //   };
        // },
        databaseUrl: undefined,
        // get databaseUrl(): string {
        //   return process.env.DATABASE_URL;
        // },
      };
    },
  ],
});
```
3. I'll create a new issue for this bug with a reproduction repo.

**Comment by imkh** [comment]
Regarding point 2, @Nikaple are you aware of any potential and undesirable side effects of setting the getters to `undefined` in the return value of the custom loader? I find it to be the "cleanest" solution to avoid the `missing property` error with TypeScript.

Other than that, I think we can close the issue.

**Comment by Nikaple** [comment]
Maybe it's the cleanest solution for now, closing
