### ISSUE TITLE
@ValidateNested doesn't work without custom validate function

### ISSUE THREAD

**Issue by imkh** [Nikaple/nest-typed-config#149]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

_Originally posted by @imkh in https://github.com/Nikaple/nest-typed-config/issues/148#issuecomment-1053080225_

>3. For some reason, having a nested configuration in the RootConfig class with the `@ValidateNested()` decorator doesn't work. You must add the custom validate function shown in the README. It seems like someone else already ran into this problem in this [issue](https://github.com/Nikaple/nest-typed-config/issues/123#issuecomment-1023223225). The [README of `class-validator`](https://github.com/typestack/class-validator/tree/142af759fcd23c96eae78c147d2069beb6648a31#validating-nested-objects) does mention that `nested object must be an instance of a class, otherwise @ValidateNested won't know what class is target of validation.` so that might be the reason?

## Expected behavior

As explained in your comment [here](https://github.com/Nikaple/nest-typed-config/issues/148#issuecomment-1053479637), "there should be no difference with builtin validate function and custom validate function.".

`@ValidateNested()` should work without the need to implement a custom validate function (especially since this decorator will be used almost always if you have nested config classes, otherwise it defeats the purpose of this feature).

## Minimal reproduction of the problem with instructions

Minimum reproduction repo here: https://github.com/imkh/nest-typed-config-issue-149

I wasn't able to reproduce the bug in the [basic example](https://github.com/Nikaple/nest-typed-config/tree/e560d6c0c27d7e5c5c25e9aa38dab1309d5d7d87/examples/basic) of this repo:

```console
$ git clone git@github.com:Nikaple/nest-typed-config.git
$ cd nest-typed-config.git
$ cd examples/basic
$ npm install @nestjs/core @nestjs/platform-express # The example wouldn't start without installing those 2 dependencies
$ npm run start # Go to http://127.0.0.1:<port>, nested config seem to work as expected
```

## What is the motivation / use case for changing the behavior?

/

## Environment

<pre><code>
Nest version:
@nestjs/cli 8.2.1
@nestjs/core 8.3.1
(both latest versions at the time of writing)

 
For Tooling issues:
- Node version: 16.13.2 
- Platform: Mac 

Others:

</code></pre>

**Comment by Nikaple** [comment]
I tried downgrade and lock the version of `class-transformer` to `0.4.0`, and it works fine. Maybe it's an issue with `class-transformer`. Needs further investigation.

**Comment by imkh** [comment]
>I tried downgrade and lock the version of class-transformer to 0.4.0, and it works fine. Maybe it's an issue with class-transformer. Needs further investigation.

Good catch, I didn't think of downgrading `class-transformer`, I only noticed after the fact that the examples shared the same `0.0.4` version as the main lib. Let me know if you need anything else.

**Comment by Nikaple** [comment]
I've edited my previous comment, please check it out :smile_cat:

**Comment by imkh** [comment]
Nice, thanks for looking into it. I'm not sure exactly what change is needed in the lib to fix the bug though and I'm not in any rush, so I don't mind waiting and using the custom validate function in the meantime.

**Comment by andrey-hohlov** [comment]
@Nikaple is there any chance for 

> Introduce a breaking change into the library, which declares class-transformer as peerDependencies.

?

We are trying ```nest-typed-config``` as a replacement for ``` @nestjs/config```. It works well except ```class-transformer``` versions mismatch. We don't wan / cannot downgrade its version.

**Comment by Nikaple** [comment]
PR #186 tries to fix this issue by import deps from root node_modules first, see:

https://github.com/Nikaple/nest-typed-config/blob/fix%2Fissue-149/lib/utils/imports.util.ts#L5

@andrey-hohlov Please let me know if you have any suggestions

**Comment by andrey-hohlov** [comment]
@Nikaple I tried new version and it works. But I'm not sure about the solution. 

```@nestjs/common``` [accepts any version](https://github.com/nestjs/nest/blob/master/packages/common/package.json ) of ```class-transformer``` and ```class-validator``` and lists them in peerDependencies.

In my opinion, the right strategy is to follow versions that are used in actual ```nestjs``` package - version ```*``` in ```peerDependencies```.

**Comment by Nikaple** [comment]
Yes, it's kinda hack, but I want to keep this lib as stable as possible, avoid breaking changes when it doesn't have to.

**Comment by svyatogor** [comment]
This solution completely breaks building monorepos unfortunately. Dynamic requires are not processed by webpack and result in `Uncaught Error: Cannot find module 'class-validator'`

**Comment by Nikaple** [comment]
@svyatogor Can you provide a minimum reproduction repo? If it's a newly introduced bug, you can file a separate issue.
