### ISSUE TITLE
Default values are overriding loaders?

### ISSUE THREAD

**Issue by danielmahon** [Nikaple/nest-typed-config#163]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Default values seem to override loaders.

## Expected behavior

I would expect loaders to always override matching default values.

NOTE: This is my first time using this library, so maybe I'm missing something simple?

## Minimal reproduction of the problem with instructions

```ts
import {
  TypedConfigModule,
  dotenvLoader,
  selectConfig,
} from 'nest-typed-config';
import { IsString, IsNumber } from 'class-validator';
import { mapKeys, camelCase } from 'lodash';

export class Config {
  @IsString()
  readonly nodeEnv: string = 'test';

  @IsString()
  readonly host: string = '127.0.0.1';

  @IsNumber()
  readonly port: number = 50051;

  @IsString()
  get url(): string {
    return `http://${this.host}:${this.port}`;
  }

  @IsString()
  get protoPath(): string {
    return this.nodeEnv === 'production' ? 'proto' : '../../../libs/proto';
  }
}

export const ConfigModule = TypedConfigModule.forRoot({
  schema: Config,
  load: [
    async () => {
      const rawEnv = dotenvLoader()();
      const mapped = mapKeys(rawEnv, (value, key) => camelCase(key));
      console.log(mapped); // nodeEnv = 'development'
      return mapped;
    },
  ],
});

export const appConfig = selectConfig(ConfigModule, Config);

console.log(appConfig); // nodeEnv = 'test' (wrong? shouldn't the loader have precedence?)
```

## What is the motivation / use case for changing the behavior?

Trying to do a simple remapping of ENV variables

## Environment

<pre><code>
Nest version: 13.9.6

 
For Tooling issues:
- Node version: v16.14.2  
- Platform: macOS 

Others:

</code></pre>

**Comment by Nikaple** [comment]
`selectConfig` only works with sync loaders, maybe remove the `async` keyword and try again?

**Comment by danielmahon** [comment]
🤦🏽‍♂️ didn't even realize I left the `async` keyword, have no need for it in this case. Seems to work fine after removing it. I'm only using `selectConfig` to grab the config in `main.ts`, DI everywhere else, but good to know. Thank you.
