### ISSUE TITLE
Nested configs won't initialize if no environment variable of that nested config is set

### ISSUE THREAD

**Issue by ravi0lii** [Nikaple/nest-typed-config#204]
## I'm submitting a...

<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

If using nested configs, nest-typed-config will not initialize a nested config when no environment variable was set for this config, even though default values for this configuration are present.

Output when starting (for the concrete ExampleConfig, see the example below):
```
Nest can't resolve dependencies of the AppService (?). Please make sure that the argument ExampleConfig at index [0] is available in the AppModule context.
```

It looks like when no environment variable for a nested config is set, the nested config will not be initialized.
When I set an environment variable that is contained inside the nested config, everything works just fine.

## Expected behavior

The nested config should be available, even though no environment variables for this config were set.

## Minimal reproduction of the problem with instructions

config.ts:
```typescript
import { Type } from 'class-transformer';
import { IsInt, Min, ValidateNested } from 'class-validator';

export class ExampleConfig {
    @IsInt()
    @Type(() => Number)
    @Min(0)
    public readonly helloWorld: number = 1337;

    @IsInt()
    @Type(() => Number)
    @Min(0)
    public readonly justANumber: number = 42;
}

export class RootConfig {
    @ValidateNested()
    @Type(() => ExampleConfig)
    public readonly example!: ExampleConfig;
}
```

app.module.ts:
```typescript
import { Global, Module } from '@nestjs/common';
import { dotenvLoader, TypedConfigModule } from 'nest-typed-config';
import { RootConfig } from './config';
import { AppService } from './app.service';

@Global()
@Module({
    imports: [
        TypedConfigModule.forRoot({
            schema: RootConfig,
            load: dotenvLoader({
                separator: '_',
            })
        })
    ],
    providers: [
        AppService
    ]
})
export class AppModule {}
```

app.service.ts:
```typescript
import { Injectable } from '@nestjs/common';
import { ExampleConfig } from '../config';

@Injectable()
export class AppService {
    constructor(
        private readonly exampleConfig: ExampleConfig
    ) {}
}
```

## Environment

<pre><code>
Nest version: 9.0.11
 
For Tooling issues:
- Node version: v18.9.0
- Platform:  Mac

Others:
Package manager: Yarn
</code></pre>

**Comment by Nikaple** [comment]
First of all, is the `example` property in `RootConfig` optional? If it's optional, you should provide default value for it, if it's not, you should add `@IsDefined` to the `example` property to make it fail early.

If you use `fileLoader` with `.env.json`, you will find out json with `example` field will pass, and initialized with default values successfully:
```json
{
    "example": {}
}
```

But if you provide an empty json file, it will fail. Default values resides in `ExampleConfig`, but as `example` property is not provided in raw config, `ExampleConfig` object will not be created.

For the solution, I'd suggest:
```ts
// add default value
public readonly example: ExampleConfig = new ExampleConfig();
```

**Comment by ravi0lii** [comment]
The fix you provided indeed works, thanks ^^
To add to this, I think that this should be documented somewhere. In my opinion, this is not intuitive behavior.
