### ISSUE TITLE
External Configuration "Validity" Check.

### ISSUE THREAD

**Issue by sethtomy** [Nikaple/nest-typed-config#213]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Expected behavior

Would it be possible to add a capability for a runtime check of the configuration? For example:

* If I have a database configuration I'd like to test a successful connection to it.
* For an external API I'd like to hit a simple endpoint.

**Comment by Nikaple** [comment]
I think "runtime check" is beyond the scope of a config module, you can implement it in the module which imports `TypedConfigModule` using nest features like `onModuleInit`. For example:

```ts
import { Module, OnModuleInit } from '@nestjs/common';
import { TypedConfigModule, fileLoader } from 'nest-typed-config';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { RootConfig } from './config';

// Register TypedConfigModule
@Module({
  imports: [
    TypedConfigModule.forRoot({
      schema: RootConfig,
      load: fileLoader(),
    }),
  ],
  providers: [AppService],
  controllers: [AppController],
})
export class AppModule implements OnModuleInit {
  constructor(private config: RootConfig) {}

  async onModuleInit() {
    throw new Error(`config check failed`);
  }
}
```

**Comment by sethtomy** [comment]
Thank you @Nikaple. The above is great and will go forward with that. Love the module!
