### ISSUE TITLE
Add ability to specify a default value for environment variable in the yaml file 

### ISSUE THREAD

**Issue by ghost** [Nikaple/nest-typed-config#362]
- [x] Feature request

## Current behavior

right now if you have such a config yaml file for example: 

```
logs:
  colorize: ${LOGS_COLORIZE}
```
and have a default value in the class 

```
export default class LoggerConfig {
  @IsBoolean()
  @Allow()
  colorize = true;
}
```

you will get an error when the app is starting 

```
Error: Environment variable is not set for variable name: 'LOGS_COLORIZE'
```

## Expected behavior

It will be nice to have the ability to specify a default value in the file itself. Like this: 

```
logs:
  colorize: ${LOGS_COLORIZE:true}
```

## What is the motivation/use case for changing the behavior?

it just will be convenient, I've seen this behavior in all config libs in java and .net.

**Comment by Nikaple** [comment]
Closed by #447
