### ISSUE TITLE
New Release for NestJS 10 support

### ISSUE THREAD

**Issue by tjbutz** [Nikaple/nest-typed-config#400]
## I'm submitting a 

- [ ] Regression 
- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Support request

## Current behavior

Current 2.6.0 release requires NestJS < 10 as a peer dependency.

```
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@">= 6.10.0 < 10" from nest-typed-config@2.6.0
npm ERR! node_modules/nest-typed-config
npm ERR!   nest-typed-config@"^2.6.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @nestjs/common@9.4.3
npm ERR! node_modules/@nestjs/common
npm ERR!   peer @nestjs/common@">= 6.10.0 < 10" from nest-typed-config@2.6.0
npm ERR!   node_modules/nest-typed-config
npm ERR!     nest-typed-config@"^2.6.0" from the root project
```

## Expected behavior

New Release with NestJS 10 support. Main already has it fixed with the following pull request:

https://github.com/Nikaple/nest-typed-config/pull/388/files

**Comment by Nikaple** [comment]
Included in release [v2.7.0](https://github.com/Nikaple/nest-typed-config/releases/tag/v2.7.0) 🎉
