### ISSUE TITLE
Different throw exception behaviour on config syntax error when an array of loaders is given

### ISSUE THREAD

**Issue by MarZab** [Nikaple/nest-typed-config#473]
## I'm submitting a...

- [ ] Regression 
- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request

## Current behavior

When there is a syntax error in an config file  ( I tested .yaml ), using a single loader throws and error. An array of loaders does not.

Issue can be traced [here](https://github.com/Nikaple/nest-typed-config/blob/9454004324afb55aec0e39c057cb3366b1efbb37/lib/typed-config.module.ts#L73).

## Expected behavior

The behaviour to be configurable or at least consistent.

## Minimal reproduction of the problem with instructions

Using config:
```yaml
with:
   an_error
   inside: the file
```

Throws:

```
export const ConfigModule = TypedConfigModule.forRoot({
  schema: RootConfig,
  load: fileLoader()
});
```

Does not throw:

```
export const ConfigModule = TypedConfigModule.forRoot({
  schema: RootConfig,
  load: [fileLoader()]
});
```

## Environment

<pre><code>
Nest version: 16.17.0
Nest-Typed-Config version: 2.7.0

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Nikaple** [comment]
Will be fixed by PR #447
