### ISSUE TITLE
Dependency lodash.set has an unpatched CVE

### ISSUE THREAD

**Issue by shprota** [Nikaple/nest-typed-config#492]
## I'm submitting a...

- [X] Regression 
- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [X] Support request

## Current behavior

The [lodash.set](https://www.npmjs.com/package/lodash.set) package has an open CVE: https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032. The maintainer of Lodash will not release a patched version, and he considers the per-method packages https://github.com/lodash/lodash/issues/3793#issuecomment-389774153.

We should be able to use [set-value](https://www.npmjs.com/package/set-value) as a drop-in replacement.

**Comment by Nikaple** [comment]
closed by #493
