### ISSUE TITLE
Environment Variable Substitution Not Working

### ISSUE THREAD

**Issue by Nathan-Bernardo** [Nikaple/nest-typed-config#496]
## I'm submitting a...

- [ ] Regression 
- [ ] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Support request

## Current behavior
Environment variable substitution defined in .env doesn't seem to be substituted into .env.yaml even when `ignoreEnvironmentVariableSubstitution: false`  for file loader.  Config file is defined below
```typescript
// .env
PORT=9000
LOADER=fileLoader
```

```typescript
app:
  somePort: ${PORT:-12345}
  envLoader: ${LOADER}
```
The current output is 
```bash
app: 
    somePort: 12345
    envLoader: undefined
```

## Expected behavior
Expected output
```bash
app:
    somePort: 9000
    envLoader: fileLoader
```

## Minimal reproduction of the problem with instructions

https://gist.github.com/Nathan-Bernardo/bcb98b2215571223299209b9088489f2

## Environment

<pre><code>
Nest version: 8.0.0
Nest-Typed-Config version: 2.9.1

 
For Tooling issues:
- Node version: 16.18.2  
- Platform: Ubuntu 18.04

**Comment by Nikaple** [comment]
Tried your code with latest version, and it's working fine for me:

<img width="782" alt="image" src="https://github.com/Nikaple/nest-typed-config/assets/24775744/e3e9f698-7635-466b-81dd-0c98bdd5f1ad">

env variable substitution for `fileLoader` was implemented in v2.9.0, please reinstall the dependencies and try again.

**Comment by taRusty** [comment]
I have the same problem. My `yml` is:

```
app:
  port: 3006
db:
  dbHost: ${DB_HOST:'localhost'}

```

And my ConfigModule looks like:

```
export const ConfigModule = TypedConfigModule.forRoot({
  schema: Config,
  load: fileLoader({ disallowUndefinedEnvironmentVariables: true }),
});
```

I was expecting throwing an error, because `DB_HOST` is not set. But got this returned:

```
Config {
app: AppConfig { port: 3006 },
db: DbConfig {
    dbHost: "${DB_HOST:'localhost'}",
}
```

Using the latest version `2.9.2`.

**Comment by Nikaple** [comment]
@taRusty see the [test files](https://github.com/Nikaple/nest-typed-config/blob/main/tests/src/.env-with-default.sub.yaml) for substitution reference, it's the same with dotenv-expand and not relevant with this issue. CodeSandbox link: https://codesandbox.io/p/devbox/brave-chatelet-jfd7zl?file=%2Fsrc%2Fconfig.ts%3A25%2C1

![image](https://github.com/Nikaple/nest-typed-config/assets/24775744/31214456-e562-4739-8fec-59f990af12e2)

**Comment by taRusty** [comment]
Oh, I had the wrong configuration then. It should be `"${DB_HOST:-localhost}" instead `"${DB_HOST:'localhost'}". And then, I was also missing `ignoreEnvironmentVariableSubstitution: false`. Didn't know the default is `true`. My bad and apologies for this. Thank you for your help.
